// Bakes prompts/*.md into a generated TS module of string constants.
//
// Why: loadPrompt() used to read these files from disk at runtime via a
// __dirname-relative path. That breaks under Next.js — its server bundler
// (webpack and Turbopack alike) rewrites __dirname to a virtual "/ROOT"
// placeholder for workspace packages it traces into the bundle, so the
// lookup silently pointed nowhere. Baking the content in at build time
// removes the runtime filesystem dependency entirely.
"use strict";
const fs = require("node:fs");
const path = require("node:path");

const promptsDir = path.join(__dirname, "../../../prompts");
const outFile = path.join(__dirname, "../src/generated/prompts.ts");

const names = fs
  .readdirSync(promptsDir)
  .filter((f) => f.endsWith(".md"))
  .map((f) => f.replace(/\.md$/, ""));

function extractPromptText(raw) {
  const fenced = raw.match(/```\n([\s\S]*?)\n```/);
  return (fenced ? fenced[1] : raw).trim();
}

const entries = names.map((name) => {
  const raw = fs.readFileSync(path.join(promptsDir, `${name}.md`), "utf-8");
  const text = extractPromptText(raw);
  return `  ${JSON.stringify(name)}: ${JSON.stringify(text)},`;
});

const contents = `// GENERATED by scripts/build-prompts.js — do not edit by hand.
// Source of truth is /prompts/*.md at the repo root; re-run \`npm run build\`
// (or \`node scripts/build-prompts.js\`) after editing a prompt.

export const PROMPTS: Record<string, string> = {
${entries.join("\n")}
};
`;

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, contents);
console.log(`Generated ${outFile} from ${names.length} prompt file(s).`);
